language: php

dist: trusty
sudo: false

cache:
  directories:
    - "$HOME/.composer"
    - vendor
env:
#  matrix:
#    - SUITE=FILE_OPS
#    - SUITE=SHORT
  global:
# API key
    secure: uC4/srZg9D0Wufpo5KQxEh1uPXgKevAlBg/W0EcMNDp9oFXREZGpZvh3pz4BVOkpZal6p/m4KPHNd5prKA87G5BZgW3Y/iTpgS1ElKizIprN9MlJ6PzBctN/UTmF5abo6AhhzdK3bfxyTNNdnOiMJP+IcP9/jbbiANUCoJGthygFDFd3wNv16jD+U96LIgckhggpPvEjWkCNpsLLMQTh26KXsZP93a2psFMPaM49HAAQtSBwNmdTNFP7iLfzDSeaNPcS3dxmu7zX/HWse3YOJefaxbsv9Xu8bp8toQZzsbe+QWI6leJvhsc/c/5GXUphry4z1WIz1hRJYZP8hhiVg+NzlHVPIDMWzObsWe9IWsAJJR0VHIlaYxpncweF3R32xyID69Ps2OBKtJqUAfBbxJRALfLXdqMqw3piNmNlZNhZRhhC2kScfRvV81uAoUsElRdOuBLL9dYZROEhTwqTEJLE5EcktmGL+qAxi4eUSNqJZDgqRL5lgR3JJFNQ9d/n+5bGqhsQ7t4U0Fo6Xh6pe48gNYT+JyAMWCmsGR9c/EvoDRYqxcLrVVoMMzcP0ED94DMeQElgV6C0nELRHvW/l/9kwtl7IKWUiv+xQKVvWJoVDJs9rrkzbQyBRDmJB+paHnx69liLCnusxTrTW6gDKG1E666ue/yqrKFGUHxeTf4=

php:
- 7.1
- 7.0
- 5.6
- hhvm

before_install:
- echo $TRAVIS_PHP_VERSION

before_script:
- bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* && "$TRAVIS_PHP_VERSION" != *"7.1"*
  ]]; then phpenv config-rm xdebug.ini; else mkdir -p ~/.phpenv/versions/hhvm/etc;
  fi;'
- echo "date.timezone = Europe/London" >> .date-timezone.ini && phpenv config-add
  .date-timezone.ini
- composer install
- bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* && "$TRAVIS_PHP_VERSION" != *"7.1"*
  ]]; then echo "zend_extension = xdebug.so" >> .xdebug.ini && phpenv config-add .xdebug.ini;
  fi;'

script:
#- bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"*  && "$TRAVIS_PHP_VERSION" != *"7.1"*
#  ]]; then vendor/bin/phpunit --coverage-clover coverage.xml --testsuite $SUITE; else
#  vendor/bin/phpunit --testsuite $SUITE; fi;'
- bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"*  && "$TRAVIS_PHP_VERSION" != *"7.1"*
  ]]; then vendor/bin/phpunit --coverage-clover coverage.xml; else
  vendor/bin/phpunit; fi;'

after_success:
- bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"*  && "$TRAVIS_PHP_VERSION" != *"7.1"*
  ]]; then chmod 777 coverage.xml && bash <(curl -s https://codecov.io/bash); fi;'

notifications:
  on_success: change
  on_failure: always

matrix:
  fast_finish: true
