language: php

php:
  - 7.0
  - hhvm

before_install:
 - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;'
 - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then mkdir -p ~/.phpenv/versions/hhvm/etc/conf.d; fi;'

before_script:
 - composer require --dev satooshi/php-coveralls
 - phpenv config-add .php.travis.ini

script:
 - phpunit -v --coverage-clover build/logs/clover.xml

after_script:
 - chmod 777 build/logs/clover.xml
 - php vendor/bin/coveralls -v

notifications:
 on_success: change
 on_failure: always

matrix:
  fast_finish: true