language: php
sudo: false

cache:
  directories:
    - vendor

std: &std
  before_script:
    - phpenv config-rm xdebug.ini
    - echo "date.timezone = Europe/London" >> .date-timezone.ini
    - phpenv config-add .date-timezone.ini
    - composer install
    - echo "zend_extension = xdebug.so" >> .xdebug.ini
    - phpenv config-add .xdebug.ini
  script: vendor/bin/phpunit --coverage-clover coverage.xml
  after_success:
    - chmod 777 coverage.xml
    - bash <(curl -s https://codecov.io/bash)


jobs:
  include:
    - php: 7.1
      before_script:
        - echo "date.timezone = Europe/London" >> .date-timezone.ini
        - phpenv config-add .date-timezone.ini
        - composer install
      script: vendor/bin/phpunit
    - php: hhvm
      before_script:
        - mkdir -p ~/.phpenv/versions/hhvm/etc
        - echo "date.timezone = Europe/London" >> .date-timezone.ini
        - phpenv config-add .date-timezone.ini
        - composer install
    - <<: *std
      php: "7.0"
    - <<: *std
      php: 5.6
